name: ShopTeleport
main: no.nytt1.shopteleport.ShopTeleport
version: 0.7.4
authors: [BoXHocK]
description: Teleports you to your or someone's shop!

commands:
   setshop:
      description: Set your shop's warp position.
      usage: /<command>
      permission: shopteleport.setshop
      permission-message: You dont have permissions for that command!
   delshop:
      description: Deletes your shop.
      usage: /<command>
      permission: shopteleport.delshop
      permission-message: You dont have permissions for that command!
   shop:
      description: Teleports you to your/someone's shop.
      usage: /<command> <player>
      permission: shopteleport.shop
      permission-message: You dont have permissions for that command!
      
permissions:
    shopteleport.*:
        description: Basic ShopTeleport commands.
        children:
            shopteleport.setshop: true
            shopteleport.shop: true
            shopteleport.delshop: true
            shopteleport.admin: false
            shopteleport.nolimit: false
    shopteleport.staff.*:
        description: Full ShopTeleport access.
        children:
            shopteleport.setshop: true
            shopteleport.shop: true
            shopteleport.delshop: true
            shopteleport.admin: true
            shopteleport.nolimit: true
    shopteleport.setshop:
        description: Set your shops warp position.
        default: false
    shopteleport.shop:
        description: Teleports you to your/someone's shop.
        default: true
    shopteleport.delshop:
        description: Deletes your shop.
        default: false
    shopteleport.admin:
        description: Admin Commands.
        default: op
    shopteleport.nolimit:
        description: Gives the user no limits.
        default: false